site:
  title: JReleaser
  url: https://jreleaser.org
  start_page: guide::index.adoc
content:
  sources:
  - url: https://github.com/jreleaser/jreleaser.github.io.git
    branches: main
    start_path: docs

ui:
  bundle:
    url: ui-bundle.zip
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files: [ .nojekyll ]
  - path: .nojekyll

