site:
  title: JReleaser
  url: https://jreleaser.org
  start_page: guide::index.adoc

content:
  sources:
    - url: ./
      branches: main
      start_path: docs

ui:
  bundle:
    url: ui-bundle.zip
  supplemental_files: './supplemental_ui'

asciidoc:
  extensions:
    - ./extensions/tabs-block/extension
